# Generated by Django 4.0.5 on 2022-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_TALLY', '0002_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_itemcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('under', models.CharField(max_length=100, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('batches', models.CharField(max_length=10, null=True)),
                ('trackdate', models.CharField(max_length=10, null=True)),
                ('expirydate', models.CharField(max_length=10, null=True)),
                ('gst_applicable', models.CharField(max_length=100, null=True)),
                ('typ_sply', models.CharField(max_length=100)),
                ('set_alter', models.CharField(max_length=100)),
                ('rate_of_duty', models.IntegerField()),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('per', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit_compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=100)),
                ('f_unit', models.CharField(max_length=100, null=True)),
                ('conversion', models.IntegerField()),
                ('s_unit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit_simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('formal_name', models.CharField(max_length=100)),
                ('uqc', models.CharField(max_length=100)),
                ('decimal', models.IntegerField()),
            ],
        ),
    ]
